# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNoEnvVarSecrets
metadata: # kpt-merge: /no-secrets-as-env-vars
  name: no-secrets-as-env-vars
  annotations:
    configmanagement.gke.io/cluster-selector: select-env-qa
    # This constraint is not certified by CIS.
    description: "Prohibits secrets as environment variables in container definitions; instead, use mounted secret files in data volumes."
    bundles.validator.forsetisecurity.org/cis-k8s-v1.5.1: 5.4.1
spec:
  enforcementAction: dryrun
  match:
    excludedNamespaces:
    - kube-system