apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: secret-admin
  annotations:
    configmanagement.gke.io/cluster-selector: select-env-qa
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]