steps:
- name: 'bash'
  args: ['echo', 'CustomMsg: $_CUSTOM_MSG\nCommitSHA: $COMMIT_SHA']
substitutions:
  _CUSTOM_MSG: From Variables
logsBucket: 'gcs://main-us-central1-e887/$PROJECT_ID'
serviceAccount: 'projects/shared-network-e887/serviceAccounts/cb-ci-user'
# options:
#   logging: GCS_ONLY