steps:
- name: 'bash'
  args: ['echo', 'CustomMsg: $_TRIGGER_VAR_EXAMPLE\nCommitSHA: $COMMIT_SHA']
substitutions:
  _TRIGGER_VAR_EXAMPLE: Default Value
logsBucket: 'gcs://main-us-central1-e887'
serviceAccount: 'projects/shared-network-e887/serviceAccounts/cb-ci-user@shared-network-e887.iam.gserviceaccount.com'
options:
  logging: GCS_ONLY