steps:
- name: 'bash'
  args: ['echo', 'CustomMsg: $_TRIGGER_VAR_EXAMPLE\nCommitSHA: $COMMIT_SHA']
substitutions:
  _TRIGGER_VAR_EXAMPLE: Default Value
logsBucket: 'gcs://main-us-central1-e887'
serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/cb-ci-user@cloudbuild-sa@${PROJECT_NUMBER}.iam.gserviceaccount.com'
options:
  dynamic_substitutions: true
  # logging: GCS_ONLY