build:
  logs_bucket: gs://$_CB_LOGS_BUCKET/$TRIGGER_NAME/$BRANCH_NAME
  images:
  - us-central1-docker.pkg.dev/$_SS_PROJECT_ID/main/$TRIGGER_NAME/python:$COMMIT_SHA
  options:
    # logging: CLOUD_LOGGING_ONLY
    dynamic_substitutions: true
  steps:
  - args:
    - pack
    - build
    - us-central1-docker.pkg.dev/$_SS_PROJECT_ID/main/$TRIGGER_NAME/python:$COMMIT_SHA
    - --builder
    - gcr.io/buildpacks/builder
    dir: cloudbuild/buildpacks
    name: gcr.io/k8s-skaffold/pack
  substitutions:
    _SS_PROJECT_ID: "shared-network-0d54"
    _CB_LOGS_BUCKET: "cloudbuild-us-central1-fd8e"
github:
  name: anthos
  owner: Manny2014
  push:
    branch: ^master$
includedFiles:
- cloudbuild/buildpacks/**
name: buildpack
serviceAccount: projects/dev-playground-ea99/serviceAccounts/cloudbuild-sa@dev-playground-ea99.iam.gserviceaccount.com